name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Check out the latest code
      uses: actions/checkout@v4

    - name: 2. Set up the Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 2.5 Install OpenCV System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx

    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 3.5 Create directory structure
      run: mkdir -p output

    - name: 4. Execute pytest
      run: |
        pytest

    - name: 5. Archive processed images
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: processed-outlines
        path: output/